name: noiseflow

channels:
  - conda-forge
dependencies:
  - cmake >=3.18.0
  - fftw >=3.3.10
  - openblas # only for windows
  - pybind11 >=2.10.4
  - xtensor
  - xsimd =8.0.5
  - xtl 
  - xtensor-blas >=0.20.0
  - xtensor-python >=0.26.1
