package:
  name: noiseflow
  version: 0.0.1

source:
  path: ..

build:
  number: 0

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - setuptools
    - poetry-core

  host:
    - python {{ python }}
    - pip
    - fftw
    - cmake

  run:
    - python >=3.9
    - fftw
    - matplotlib
    - scipy 
    - numba
    - h5py
    - tqdm 
    - joblib 
    - faker 


test:
  requires:
    - pytest
  imports:
    - noiseflow


about:
  summary: An ambient noise package.
  license: Apache-2.0
  license_file: LICENSE
