{% set org = "Environmental-Seismology" %}
{% set name = "noiseflow" %}
{% set version = "0.0.6a" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ea3b6f13df02bf347abddd979bfa146168c8c56585e1a06b5bcce942107d92d9

build:
  number: 0

requirements:
  build:
    - "{{ compiler('cxx') }}"
    # - cross-python_{{ target_platform }}
    - python
    - numpy
    - cmake
    - setuptools
    - poetry-core
    - pip

  host:
    - python
    - numpy
    - pip
    - fftw
    - pybind11
    - xtensor
    - xtensor-python
    - xsimd
    - xtl 
    - xtensor-blas

  run:
    - python >=3.9
    - numpy
    - scipy
    - matplotlib
    - h5py
    - joblib 
    - tqdm 
    - obspy
    - faker
    


test:
  requires:
    - pytest
  imports:
    - noiseflow


about:
  summary: An ambient noise package.
  license: Apache-2.0
  license_file: LICENSE
