{% set org = "Environmental-Seismology" %}
{% set name = "noiseflow" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e84276bee22d7f8f67640ee94faec1a079f0336b2311ab12acbe41756c28178b

build:
  number: 0

requirements:
  build:
    - "{{ compiler('cxx') }}"
    # - cross-python_{{ target_platform }}
    - python
    - numpy
    - cmake
    - setuptools
    - poetry-core
    - pip
    - obspy

  host:
    - python
    - numpy
    - pip
    - fftw
    - pybind11
    - obspy
    # - xtensor
    # - xtensor-python
    # - xsimd
    # - xtl 
    # - xtensor-blas

  run:
    - python >=3.9
    - numpy
    - scipy
    - matplotlib
    - h5py
    - joblib 
    - tqdm 
    - obspy
    


test:
  requires:
    - pytest
  imports:
    - noiseflow


about:
  summary: An ambient noise package.
  license: Apache-2.0
  license_file: LICENSE
