{% set org = "Environmental-Seismology" %}
{% set name = "noiseflow" %}
{% set version = "0.0.6d" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2ecc462c3e1feb37f603f4b6dfa3be78bddedef621c72034ed0abec6710ebf35

build:
  number: 0
  skip: True  # [python_impl == 'pypy']
  


outputs:

  - name: {{ name|lower }}
    script: build_osx.sh  # [osx]
    script: build_linux.sh  # [linux]
    script: build_win.bat  # [win]

    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - python >=3.9                              
        - poetry-core
        - setuptools                          
        - cmake
        - numpy 
        - pip  
        - make  # [unix]
        - ninja    
        - llvm-openmp  
           

      host:
        - pip
        - python >=3.9
        - numpy 
        - fftw
        - pybind11
        - xtensor
        - xtensor-python
        - xsimd =8.0.5
        - xtl 
        - xtensor-blas
        - llvm-openmp  

      run:
        - numpy >=1.25.0
        - scipy =1.10.1
        - matplotlib-base
        - h5py
        - joblib 
        - tqdm 
        - obspy
        - faker



      test:
        imports:
          - noiseflow
          - noiseflow.cc
          - noiseflow.signal

about:
  home: https://github.com/{{ org }}/{{ name }}
  summary: An ambient noise package.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - OUCyf
