{% set org = "Environmental-Seismology" %}
{% set name = "noiseflow" %}
{% set version = "0.0.6b" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8edd78dbf8f9baa25a174b4699a1c3e42bd3e93fbc0c632e81071e22f8a3cb81

build:
  number: 0
  skip: True  # [python_impl == 'pypy']
  


outputs:

  - name: {{ name|lower }}
    script: install.sh  # [unix]
    script: install.bat  # [win]

    requirements:
      build:
        - "{{ compiler('cxx') }}"
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - python                              # [build_platform != target_platform]
        - poetry-core
        - setuptools                          
        - cmake
        - numpy                             

      host:
        - python
        - numpy
        - fftw
        - pybind11
        - xtensor
        - xtensor-python
        - xsimd =8.0.5
        - xtl 
        - xtensor-blas

      run:
        - numpy
        - scipy
        - matplotlib-base
        - h5py
        - joblib 
        - tqdm 
        - obspy
        - faker

      test:
        requires:
          - pytest
        imports:
          - noiseflow


about:
  summary: An ambient noise package.
  license: Apache-2.0
  license_file: LICENSE


extra:
  recipe-maintainers:
    - OUCyf