build: false

image: Visual Studio 2015

configuration: Release

platform:
  - x64
  - x86

environment:
  matrix:
      # fftw from conda-forge
    - MINICONDA: C:\Miniconda36-x64
      FFTW_INSTALL_MODE: conda-forge
      FFTW_ROOT:
      # fftw from the "official" fftw website build
    - MINICONDA: C:\Miniconda36-x64
      FFTW_INSTALL_MODE: official
      FFTW_ROOT: C:\fftw_download

matrix:
  exclude:
    - platform: x86
      MINICONDA: C:\Miniconda36-x64
    - platform: x64
      MINICONDA: C:\Miniconda36
  fast_finish: true

init:
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat %PLATFORM%
  - "set PATH=%FFTW_ROOT%;%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda install xtensor=0.21.2 -c conda-forge
  - IF "%FFTW_INSTALL_MODE%"=="official" ( Powershell.exe -File appveyor_install_fftw.ps1 ) ELSE IF "%FFTW_INSTALL_MODE%"=="conda-forge" ( conda install fftw )
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DFFTW_ROOT=%FFTW_ROOT% -DCMAKE_INSTALL_PREFIX=%MINICONDA%\\Library -DDOWNLOAD_GTEST=ON ..
  - nmake test_xtensor-fftw

before_build:
  - cd test

build_script:
  - test_xtensor-fftw.exe
