name: test
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.7", "3.8", "3.9"]
    env:
      OS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install openmp on mac
        if: matrix.os == 'macos-latest'
        run: |
          brew install libomp

      - name: Install openmp on ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libomp-dev

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}